before_script:
  - apt-get update -qq && apt-get install -y -qq python3 python3-pip
  - python3 --version
  - pip3 install -r requirements.txt
  - python3 manage.py makemigrations
  - python3 manage.py migrate

newmero_test:
  script:
    - python3 manage.py test calculator.tests calculator.computations.tests
